/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Shared/About.vue')['default']
    AboutUs: typeof import('./src/components/Home/AboutUs.vue')['default']
    Advisors: typeof import('./src/components/Committees/Advisors.vue')['default']
    CallToAction: typeof import('./src/components/About/CallToAction.vue')['default']
    CommonHero: typeof import('./src/components/Shared/CommonHero.vue')['default']
    ContactUs: typeof import('./src/components/Home/ContactUs.vue')['default']
    Events: typeof import('./src/components/Home/Events.vue')['default']
    ExecutiveMember: typeof import('./src/components/Committees/ExecutiveMember.vue')['default']
    Footer: typeof import('./src/components/Shared/Footer.vue')['default']
    Founders: typeof import('./src/components/Home/Founders.vue')['default']
    Gallery: typeof import('./src/components/Shared/Gallery.vue')['default']
    Hero: typeof import('./src/components/Home/Hero.vue')['default']
    MeetToLeadership: typeof import('./src/components/About/MeetToLeadership.vue')['default']
    Members: typeof import('./src/components/Home/Members.vue')['default']
    MemberShipForm: typeof import('./src/components/Members/MemberShipForm.vue')['default']
    MembersModal: typeof import('./src/components/Committees/MembersModal.vue')['default']
    MissionVission: typeof import('./src/components/About/MissionVission.vue')['default']
    Navbar: typeof import('./src/components/Shared/Navbar.vue')['default']
    OurMission: typeof import('./src/components/Home/OurMission.vue')['default']
    Registration: typeof import('./src/components/Home/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonial: typeof import('./src/components/Home/Testimonial.vue')['default']
    WhatWeDo: typeof import('./src/components/About/WhatWeDo.vue')['default']
    WhoWeAre: typeof import('./src/components/About/WhoWeAre.vue')['default']
  }
}
