/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Shared/About.vue')['default']
    AboutUs: typeof import('./src/components/Home/AboutUs.vue')['default']
    ContactUs: typeof import('./src/components/Home/ContactUs.vue')['default']
    Events: typeof import('./src/components/Home/Events.vue')['default']
    Footer: typeof import('./src/components/Shared/Footer.vue')['default']
    Founders: typeof import('./src/components/Home/Founders.vue')['default']
    Hero: typeof import('./src/components/Home/Hero.vue')['default']
    Members: typeof import('./src/components/Home/Members.vue')['default']
    Navbar: typeof import('./src/components/Shared/Navbar.vue')['default']
    OurMission: typeof import('./src/components/Home/OurMission.vue')['default']
    Registration: typeof import('./src/components/Home/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonial: typeof import('./src/components/Home/Testimonial.vue')['default']
  }
}
